from .identifiable import Identifiable
from .animal import Animal
from .terrestrial import Terrestrial
from .aquatic import Aquatic
from .freshwater import Freshwater
from .flying import Flying
from .walking import Walking
from .swimming import Swimming
from .river_dolphin import RiverDolphin
from .gold_dust_day_gecko import GoldDustDayGecko
from .kikakapu import Kikakapu
from .nene_goose import NeneGoose
from .opeapea import Opeapea
from .pueo import Pueo
from .ulae import Ulae
