from .aquatic import Aquatic
from .contains_animals import ContainsAnimals
from .contains_plants import ContainsPlants
from .flying import Flying
from .freshwater import Freshwater
from .identifiable import Identifiable
from .saltwater import Saltwater
from .swimming import Swimming
from .terrestrial import Terrestrial
from .walking import Walking
from .mammal import Mammal
from .reptile import Reptile
